export const START_GAME = 'startGame'
export const LOAD_GAME = 'loadGame'
export const ADD_TECH = 'appendTech'
export const REMOVE_TECH = 'removeTech'
export const UPDATE_ADDITIONAL_DISTANCE = 'updateAdditionalDistance'
export const SET_PLAYERS_REF = 'setPlayersRef'
